version: "3.9"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception-net



networks:
  inception-net:
    driver: bridge